version: '3'

services:
  # MySQL Database
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"

  # Golang CRUD API
  api:
    build:
      context: .
    container_name: api-container
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: your_database_user
      DB_PASSWORD: your_database_password
      DB_NAME: your_database_name
    ports:
      - "8080:8080"
    depends_on:
      - db
